-- IPv4 Academy V2 foundation
-- Safe to apply alongside V1 because all objects use the academy_v2 schema.

create schema if not exists academy_v2;

create table if not exists academy_v2.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'student' check (role in ('student','trainer','admin')),
  group_no text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists academy_v2.courses (
  id bigint generated by default as identity primary key,
  code text unique not null,
  title text not null,
  description text,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists academy_v2.lessons (
  id bigint generated by default as identity primary key,
  course_id bigint not null references academy_v2.courses(id) on delete cascade,
  title text not null,
  slug text unique not null,
  sort_order int not null default 0,
  content jsonb not null default '{}'::jsonb,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists academy_v2.questions (
  id bigint generated by default as identity primary key,
  course_id bigint references academy_v2.courses(id) on delete set null,
  lesson_id bigint references academy_v2.lessons(id) on delete set null,
  question_type text not null default 'mcq' check (question_type in ('mcq','true_false','short_answer','matching')),
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  answer jsonb not null default '{}'::jsonb,
  difficulty text not null default 'easy' check (difficulty in ('easy','medium','hard')),
  topic text,
  points numeric(8,2) not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists academy_v2.exams (
  id bigint generated by default as identity primary key,
  course_id bigint references academy_v2.courses(id) on delete set null,
  title text not null,
  instructions text,
  duration_minutes int not null default 20,
  pass_score numeric(5,2) not null default 60,
  attempts_limit int not null default 1,
  status text not null default 'draft' check (status in ('draft','scheduled','open','closed','archived')),
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references academy_v2.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists academy_v2.exam_questions (
  exam_id bigint not null references academy_v2.exams(id) on delete cascade,
  question_id bigint not null references academy_v2.questions(id) on delete cascade,
  sort_order int not null default 0,
  points numeric(8,2) not null default 1,
  primary key (exam_id,question_id)
);

create table if not exists academy_v2.attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references academy_v2.exams(id) on delete cascade,
  student_id uuid not null references academy_v2.profiles(id) on delete cascade,
  status text not null default 'in_progress' check (status in ('in_progress','submitted','graded','expired')),
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  score numeric(6,2),
  passed boolean,
  duration_seconds int
);

create table if not exists academy_v2.attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references academy_v2.attempts(id) on delete cascade,
  question_id bigint not null references academy_v2.questions(id) on delete cascade,
  answer jsonb not null default '{}'::jsonb,
  is_correct boolean,
  points_awarded numeric(8,2) not null default 0,
  answered_at timestamptz not null default now(),
  unique(attempt_id,question_id)
);

create table if not exists academy_v2.practice_attempts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references academy_v2.profiles(id) on delete cascade,
  lesson_id bigint references academy_v2.lessons(id) on delete set null,
  topic text,
  question_id bigint references academy_v2.questions(id) on delete set null,
  answer jsonb not null default '{}'::jsonb,
  is_correct boolean,
  duration_seconds int,
  created_at timestamptz not null default now()
);

create table if not exists academy_v2.student_progress (
  student_id uuid not null references academy_v2.profiles(id) on delete cascade,
  course_id bigint not null references academy_v2.courses(id) on delete cascade,
  progress_pct numeric(5,2) not null default 0,
  mastery_pct numeric(5,2) not null default 0,
  streak_days int not null default 0,
  last_activity_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(student_id,course_id)
);

create table if not exists academy_v2.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references academy_v2.profiles(id) on delete cascade,
  event_key text not null,
  title text not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,event_key)
);

create table if not exists academy_v2.achievements (
  id bigint generated by default as identity primary key,
  code text unique not null,
  title text not null,
  description text,
  icon text,
  rule jsonb not null default '{}'::jsonb
);

create table if not exists academy_v2.student_achievements (
  student_id uuid not null references academy_v2.profiles(id) on delete cascade,
  achievement_id bigint not null references academy_v2.achievements(id) on delete cascade,
  earned_at timestamptz not null default now(),
  primary key(student_id,achievement_id)
);

create index if not exists idx_v2_attempts_student on academy_v2.attempts(student_id,started_at desc);
create index if not exists idx_v2_practice_student on academy_v2.practice_attempts(student_id,created_at desc);
create index if not exists idx_v2_questions_topic on academy_v2.questions(topic,is_active);
create index if not exists idx_v2_notifications_user on academy_v2.notifications(user_id,created_at desc);

alter table academy_v2.profiles enable row level security;
alter table academy_v2.courses enable row level security;
alter table academy_v2.lessons enable row level security;
alter table academy_v2.questions enable row level security;
alter table academy_v2.exams enable row level security;
alter table academy_v2.exam_questions enable row level security;
alter table academy_v2.attempts enable row level security;
alter table academy_v2.attempt_answers enable row level security;
alter table academy_v2.practice_attempts enable row level security;
alter table academy_v2.student_progress enable row level security;
alter table academy_v2.notifications enable row level security;
alter table academy_v2.achievements enable row level security;
alter table academy_v2.student_achievements enable row level security;

-- Base helper. Trainer/admin checks are enforced in SQL, not trusted in the UI.
create or replace function academy_v2.is_staff()
returns boolean
language sql
stable
as $$
  select exists(
    select 1 from academy_v2.profiles p
    where p.id = auth.uid() and p.role in ('trainer','admin') and p.is_active
  );
$$;

create policy v2_profiles_self on academy_v2.profiles for select using (id=auth.uid() or academy_v2.is_staff());
create policy v2_courses_read on academy_v2.courses for select using (status='published' or academy_v2.is_staff());
create policy v2_lessons_read on academy_v2.lessons for select using (
  is_published or academy_v2.is_staff()
);
create policy v2_questions_read on academy_v2.questions for select using (is_active or academy_v2.is_staff());
create policy v2_exams_read on academy_v2.exams for select using (academy_v2.is_staff() or status in ('scheduled','open'));
create policy v2_exam_questions_read on academy_v2.exam_questions for select using (
  exists(select 1 from academy_v2.exams e where e.id=exam_id and (e.status in ('scheduled','open') or academy_v2.is_staff()))
);
create policy v2_attempts_self on academy_v2.attempts for select using (student_id=auth.uid() or academy_v2.is_staff());
create policy v2_attempt_answers_self on academy_v2.attempt_answers for select using (
  exists(select 1 from academy_v2.attempts a where a.id=attempt_id and (a.student_id=auth.uid() or academy_v2.is_staff()))
);
create policy v2_practice_self on academy_v2.practice_attempts for select using (student_id=auth.uid() or academy_v2.is_staff());
create policy v2_progress_self on academy_v2.student_progress for select using (student_id=auth.uid() or academy_v2.is_staff());
create policy v2_notifications_self on academy_v2.notifications for select using (user_id=auth.uid());
create policy v2_achievements_read on academy_v2.achievements for select using (true);
create policy v2_student_achievements_self on academy_v2.student_achievements for select using (student_id=auth.uid() or academy_v2.is_staff());

-- Dashboard summaries: first V2 analytics layer.
create or replace view academy_v2.student_dashboard_summary as
select
  p.id as student_id,
  p.full_name,
  p.group_no,
  coalesce(round(avg(a.score)::numeric,2),0) as avg_exam_score,
  count(a.id)::int as exam_attempts,
  coalesce(round(avg(case when pa.is_correct then 100 else 0 end)::numeric,2),0) as practice_accuracy,
  count(pa.id)::int as practice_attempts
from academy_v2.profiles p
left join academy_v2.attempts a on a.student_id=p.id and a.status in ('graded','submitted')
left join academy_v2.practice_attempts pa on pa.student_id=p.id
group by p.id,p.full_name,p.group_no;

create or replace view academy_v2.trainer_group_summary as
select
  coalesce(nullif(p.group_no,''),'غير محدد') as group_no,
  count(*)::int as students,
  count(*) filter(where p.is_active)::int as active_students
from academy_v2.profiles p
where p.role='student'
group by 1;

create or replace view academy_v2.trainer_topic_summary as
select
  coalesce(pa.topic,'غير محدد') as topic,
  count(*)::int as attempts,
  round(avg(case when pa.is_correct then 100 else 0 end)::numeric,2) as accuracy
from academy_v2.practice_attempts pa
group by 1;


-- Create a V2 profile automatically for every new Auth user.
-- Role is intentionally always student here; trainer/admin elevation is administrative only.
create or replace function academy_v2.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = academy_v2, public
as $$
begin
  insert into academy_v2.profiles(id,full_name,role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(coalesce(new.email,'متدرب'), '@', 1), 'متدرب'),
    'student'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_v2 on auth.users;
create trigger on_auth_user_created_v2
after insert on auth.users
for each row execute procedure academy_v2.handle_new_user();

grant usage on schema academy_v2 to anon, authenticated;
grant select on academy_v2.courses,
              academy_v2.lessons,
              academy_v2.questions,
              academy_v2.exams,
              academy_v2.exam_questions,
              academy_v2.achievements to anon, authenticated;

grant select on academy_v2.profiles,
              academy_v2.attempts,
              academy_v2.attempt_answers,
              academy_v2.practice_attempts,
              academy_v2.student_progress,
              academy_v2.notifications,
              academy_v2.student_achievements to authenticated;

-- PostgREST must expose academy_v2 in Supabase Dashboard:
-- Settings → API → Exposed schemas → add academy_v2.


-- V3.30: write policies for real student attempts and staff management.
drop policy if exists v2_attempts_insert on academy_v2.attempts;
create policy v2_attempts_insert on academy_v2.attempts
for insert with check (student_id=auth.uid());

drop policy if exists v2_attempts_update on academy_v2.attempts;
create policy v2_attempts_update on academy_v2.attempts
for update using (student_id=auth.uid() or academy_v2.is_staff())
with check (student_id=auth.uid() or academy_v2.is_staff());

drop policy if exists v2_attempt_answers_insert on academy_v2.attempt_answers;
create policy v2_attempt_answers_insert on academy_v2.attempt_answers
for insert with check (
  exists(select 1 from academy_v2.attempts a where a.id=attempt_id and (a.student_id=auth.uid() or academy_v2.is_staff()))
);

drop policy if exists v2_attempt_answers_update on academy_v2.attempt_answers;
create policy v2_attempt_answers_update on academy_v2.attempt_answers
for update using (
  exists(select 1 from academy_v2.attempts a where a.id=attempt_id and (a.student_id=auth.uid() or academy_v2.is_staff()))
)
with check (
  exists(select 1 from academy_v2.attempts a where a.id=attempt_id and (a.student_id=auth.uid() or academy_v2.is_staff()))
);

drop policy if exists v2_questions_staff_insert on academy_v2.questions;
create policy v2_questions_staff_insert on academy_v2.questions
for insert with check (academy_v2.is_staff());

drop policy if exists v2_questions_staff_update on academy_v2.questions;
create policy v2_questions_staff_update on academy_v2.questions
for update using (academy_v2.is_staff()) with check (academy_v2.is_staff());

drop policy if exists v2_questions_staff_delete on academy_v2.questions;
create policy v2_questions_staff_delete on academy_v2.questions
for delete using (academy_v2.is_staff());

drop policy if exists v2_exams_staff_insert on academy_v2.exams;
create policy v2_exams_staff_insert on academy_v2.exams
for insert with check (academy_v2.is_staff());

drop policy if exists v2_exams_staff_update on academy_v2.exams;
create policy v2_exams_staff_update on academy_v2.exams
for update using (academy_v2.is_staff()) with check (academy_v2.is_staff());

drop policy if exists v2_exams_staff_delete on academy_v2.exams;
create policy v2_exams_staff_delete on academy_v2.exams
for delete using (academy_v2.is_staff());

drop policy if exists v2_exam_questions_staff_insert on academy_v2.exam_questions;
create policy v2_exam_questions_staff_insert on academy_v2.exam_questions
for insert with check (academy_v2.is_staff());

drop policy if exists v2_exam_questions_staff_update on academy_v2.exam_questions;
create policy v2_exam_questions_staff_update on academy_v2.exam_questions
for update using (academy_v2.is_staff()) with check (academy_v2.is_staff());

drop policy if exists v2_exam_questions_staff_delete on academy_v2.exam_questions;
create policy v2_exam_questions_staff_delete on academy_v2.exam_questions
for delete using (academy_v2.is_staff());

create index if not exists idx_v2_attempt_answers_question on academy_v2.attempt_answers(question_id);
create index if not exists idx_v2_exam_questions_question on academy_v2.exam_questions(question_id);
